### PR TITLE
Implementing MLCube CLI.

### PR DESCRIPTION
**Pull request by sergey-serebryakov**
This commit enables running MLCube on different platforms using mlcube CLI - a single entry point for all MLCube runners. The following is supported:
- `mlcube pull --mlcube=URL --branch=NAME`: Pull MLCube from some remote location. GitHub is the only supported protocol.
- `mlcube verify --mlcube=PATH`: Verify MLCube metadata.
- `mlcube describe --mlcube=PATH`: Describe this MLCube.
- `mlcube configure --mlcube=PATH --platform=PLATFORM`: Configure environment for MLCube ML workload.
- `mlcube run --mlcube=PATH --platform=PLATFORM --task=TASK`: Run MLCube ML workload.

Supported MLCube runners: `docker`, `podman` and `singluarity`.
Unsupported MLCube runners: `SSH`, `GCP` and `K8S`.

### Example

Get MLCube - MLCommons SSD Training Reference Benchmark:
```shell
mlcube pull --mlcube=https://github.com/sergey-serebryakov/mlcube_train_ssd --branch=feature/docker_args
cd ./mlcube_train_ssd
```

See what's inside:
```shell
mlcube describe

MLCube
  Path = /tmp/tttt/mlcube_train_ssd
  Name = mlcommons_training_ssd:0.1.0
  Platforms:
    Platform = {'name': 'docker', 'version': '>=18.01'}, container = {'command': 'docker', 'run_args': '--rm  --gpus=all --net=host --uts=host --ipc=host --ulimit stack=67108864 --ulimit memlock=-1 --privileged=true --security-opt seccomp=unconfined -v /dev/shm:/dev/shm', 'image': 'mlcommons/train_ssd:0.0.1'}
    Platform = {'name': 'podman', 'version': '>=1.6.4'}, container = {'command': 'docker', 'run_args': '--rm  --net=host --uts=host --ipc=host --ulimit stack=67108864 --ulimit memlock=-1 -e NVIDIA_VISABLE_DEVICES=ALL --privileged=true --security-opt seccomp=unconfined -v /dev/shm:/dev/shm', 'image': 'mlcommons/train_ssd:0.0.1'}
  Tasks:
    Task = train
      Inputs:
        data_dir (directory): See download::data_dir.
        parameters_file (file): File with input parameters, such as number of epochs.
      Outputs:
    Task = download
      Inputs:
      Outputs:
        cache_dir (directory): Cache directory for compressed datasets and annotations (COCO 2017). Will contain the
            following files: `train2017.zip`, `val2017.zip` and `annotations_trainval2017.zip`. Total size is ~ 20G. If
            these files are not present, they will be downloaded here.
        data_dir (directory): Directory for uncompressed datasets. Will contain the following subdirectories:
            `train2017`, `val2017` and `annotations`. Total size is ~ 20G. This is basically the content of archives in
            **cache_dir**.
Run this MLCube:
  Configure MLCube:
    mlcube configure --mlcube=/tmp/tttt/mlcube_train_ssd --platform=docker|podman
  Run MLCube tasks:
    mlcube run --mlcube=/tmp/tttt/mlcube_train_ssd --task=train --platform=docker|podman
    mlcube run --mlcube=/tmp/tttt/mlcube_train_ssd --task=download --platform=docker|podman
```

Configure MLCube (optional):
```shell
mlcube configure --platform=docker
```

Download data (40 GB of available disk space is required in MLCube's workspace):
```shell
mlcube run --task=download --platform=docker
```

Run training benchmark:
```shell
mlcube run --task=train --platform=docker
```

### CODE REVIEW

**Comment by sergey-serebryakov** [comment]
@sub-mod @xyhuang @bitfort @dfeddema 
Please, take a look. Once merged, there's one more tiny PR coming to support compact MLCubes (I already have it).

**Comment by xyhuang** [comment]
this has probably been discussed but excuse me for being out of context of the decision:
just curious, how would the command be like for ssh, k8s and gcp, are they going to use different commands while the docker, podman and singularity use `mlcube`?

**Comment by sergey-serebryakov** [comment]
@xyhuang Currently, it's just simple rule-based approach to select a runner. MLCube loads a platform configuration file and tries to guess what runner it should be using. Once we introduce schemas and unify configurations for ssh, k8s and gcp, it should be exactly the same. MLCube CLI does not replace runners CLI - it just provides a thin layer and implements that single-entry point thing for running cubes.

**Review by bitfort — APPROVED** [review]
Looks great! Let's push forward! Thanks Sergey!

**Comment by sergey-serebryakov** [comment]
Changes committed in #183.

**Pull request closed without merging**
